name: Build debian packages
on:
  workflow_dispatch: {}
jobs:
  build-deb-packages:
    name: Ubuntu Devel
    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: devel
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Prepare sources
      uses: kohlerdominik/docker-run-action@v2.0.0
      id: sources-prepare
      with:
        image: ubuntu:${{ env.UBUNTU_VERSION }}
        environment: 'TERM=dumb

          DEBIAN_FRONTEND=noninteractive

          DEBCONF_NONINTERACTIVE_SEEN=true

          DEB_BUILD_PROFILE=nocheck

          '
        volumes: '${{ github.workspace }}:${{ github.workspace }}

          '
        workdir: ${{ github.workspace }}
        shell: bash
        run: "apt update -y\napt install -y git-buildpackage\napt build-dep -y . --build-profiles=${DEB_BUILD_PROFILE}\n\
          mkdir sources\ngit config --system --add safe.directory \"${PWD}\"\ngbp\
          \ buildpackage --git-export-dir=\"$PWD/sources\" \\\n  --git-ignore-branch\
          \ -S --no-sign --build-profiles=${DEB_BUILD_PROFILE}\nfind sources\npkg_dsc=$(ls\
          \ -1 sources/*.dsc)\n(\n  echo \"pkg-dsc=$(basename \"${pkg_dsc}\")\"\n\
          \  echo \"pkg-dsc-path=${{ github.workspace }}/${pkg_dsc}\"\n) >> \"${GITHUB_OUTPUT}\"\
          \n"
    - name: Save source package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debian-source
        path: ${{ github.workspace }}/sources
        if-no-files-found: error
    - name: Build debian packages
      uses: canonical/desktop-engineering/gh-actions/common/build-debian@main
      with:
        docker-image: ubuntu:${{ env.UBUNTU_VERSION }}
        from-sources-file: ${{ steps.sources-prepare.outputs.pkg-dsc-path }}
        extra-source-build-deps: ''
